spring:
  profiles:
    active: dev
  application:
    name: hotel-gateway
server:
  port: 18130

mybatis:
  type-aliases-package: com.rias.sharing.life.hotel.gateway.entity

snow-flake:
  date-center:
    id: 1
  machine:
    id: 1

hotel:
  order:
    expire-time: 15


