spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/share_life_message?&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    stream:
      bindings:
        inputTransaction:
          destination: dev_transaction_exchange
        outputTransaction:
          destination: dev_transaction_exchange
  rabbitmq:
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/