spring:
  profiles:
    active: dev
  application:
    name: hotel
server:
  port: 18120

mybatis:
  type-aliases-package: com.rias.sharing.life.user.entity

snow-flake:
  date-center:
    id: 1
  machine:
    id: 1


